// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: storage/common.proto

package storage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_UNKNOWN         HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING         HealthCheckResponse_ServingStatus = 1
	HealthCheckResponse_NOT_SERVING     HealthCheckResponse_ServingStatus = 2
	HealthCheckResponse_SERVICE_UNKNOWN HealthCheckResponse_ServingStatus = 3
)

// Enum value maps for HealthCheckResponse_ServingStatus.
var (
	HealthCheckResponse_ServingStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
		3: "SERVICE_UNKNOWN",
	}
	HealthCheckResponse_ServingStatus_value = map[string]int32{
		"UNKNOWN":         0,
		"SERVING":         1,
		"NOT_SERVING":     2,
		"SERVICE_UNKNOWN": 3,
	}
)

func (x HealthCheckResponse_ServingStatus) Enum() *HealthCheckResponse_ServingStatus {
	p := new(HealthCheckResponse_ServingStatus)
	*p = x
	return p
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_storage_common_proto_enumTypes[0].Descriptor()
}

func (HealthCheckResponse_ServingStatus) Type() protoreflect.EnumType {
	return &file_storage_common_proto_enumTypes[0]
}

func (x HealthCheckResponse_ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_ServingStatus.Descriptor instead.
func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_storage_common_proto_rawDescGZIP(), []int{10, 0}
}

// TenantID represents a unique tenant identifier
type TenantID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantID) Reset() {
	*x = TenantID{}
	mi := &file_storage_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantID) ProtoMessage() {}

func (x *TenantID) ProtoReflect() protoreflect.Message {
	mi := &file_storage_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantID.ProtoReflect.Descriptor instead.
func (*TenantID) Descriptor() ([]byte, []int) {
	return file_storage_common_proto_rawDescGZIP(), []int{0}
}

func (x *TenantID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// EntityID represents a unique entity identifier
type EntityID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityID) Reset() {
	*x = EntityID{}
	mi := &file_storage_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityID) ProtoMessage() {}

func (x *EntityID) ProtoReflect() protoreflect.Message {
	mi := &file_storage_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityID.ProtoReflect.Descriptor instead.
func (*EntityID) Descriptor() ([]byte, []int) {
	return file_storage_common_proto_rawDescGZIP(), []int{1}
}

func (x *EntityID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// RecordID represents a unique record identifier
type RecordID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      *TenantID              `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	EntityId      *EntityID              `protobuf:"bytes,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordID) Reset() {
	*x = RecordID{}
	mi := &file_storage_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordID) ProtoMessage() {}

func (x *RecordID) ProtoReflect() protoreflect.Message {
	mi := &file_storage_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordID.ProtoReflect.Descriptor instead.
func (*RecordID) Descriptor() ([]byte, []int) {
	return file_storage_common_proto_rawDescGZIP(), []int{2}
}

func (x *RecordID) GetTenantId() *TenantID {
	if x != nil {
		return x.TenantId
	}
	return nil
}

func (x *RecordID) GetEntityId() *EntityID {
	if x != nil {
		return x.EntityId
	}
	return nil
}

func (x *RecordID) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// SchemaID represents a schema identifier
type SchemaID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      *TenantID              `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version       int32                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaID) Reset() {
	*x = SchemaID{}
	mi := &file_storage_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaID) ProtoMessage() {}

func (x *SchemaID) ProtoReflect() protoreflect.Message {
	mi := &file_storage_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaID.ProtoReflect.Descriptor instead.
func (*SchemaID) Descriptor() ([]byte, []int) {
	return file_storage_common_proto_rawDescGZIP(), []int{3}
}

func (x *SchemaID) GetTenantId() *TenantID {
	if x != nil {
		return x.TenantId
	}
	return nil
}

func (x *SchemaID) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SchemaID) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

// DataRecord represents a data record
type DataRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *RecordID              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          *structpb.Struct       `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Schema        *SchemaID              `protobuf:"bytes,3,opt,name=schema,proto3" json:"schema,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Version       int64                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataRecord) Reset() {
	*x = DataRecord{}
	mi := &file_storage_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataRecord) ProtoMessage() {}

func (x *DataRecord) ProtoReflect() protoreflect.Message {
	mi := &file_storage_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataRecord.ProtoReflect.Descriptor instead.
func (*DataRecord) Descriptor() ([]byte, []int) {
	return file_storage_common_proto_rawDescGZIP(), []int{4}
}

func (x *DataRecord) GetId() *RecordID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *DataRecord) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DataRecord) GetSchema() *SchemaID {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *DataRecord) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *DataRecord) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *DataRecord) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Location represents the physical location of data
type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Length        int64                  `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	RowGroup      int32                  `protobuf:"varint,4,opt,name=row_group,json=rowGroup,proto3" json:"row_group,omitempty"`
	Compressed    bool                   `protobuf:"varint,5,opt,name=compressed,proto3" json:"compressed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_storage_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_storage_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_storage_common_proto_rawDescGZIP(), []int{5}
}

func (x *Location) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *Location) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Location) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *Location) GetRowGroup() int32 {
	if x != nil {
		return x.RowGroup
	}
	return 0
}

func (x *Location) GetCompressed() bool {
	if x != nil {
		return x.Compressed
	}
	return false
}

// TimeRange represents a time range filter
type TimeRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeRange) Reset() {
	*x = TimeRange{}
	mi := &file_storage_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRange) ProtoMessage() {}

func (x *TimeRange) ProtoReflect() protoreflect.Message {
	mi := &file_storage_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRange.ProtoReflect.Descriptor instead.
func (*TimeRange) Descriptor() ([]byte, []int) {
	return file_storage_common_proto_rawDescGZIP(), []int{6}
}

func (x *TimeRange) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *TimeRange) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

// QueryFilter represents a filter condition
type QueryFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Column        string                 `protobuf:"bytes,1,opt,name=column,proto3" json:"column,omitempty"`
	Operator      string                 `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"` // "eq", "ne", "gt", "gte", "lt", "lte", "in", "not_in"
	Value         *structpb.Value        `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryFilter) Reset() {
	*x = QueryFilter{}
	mi := &file_storage_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryFilter) ProtoMessage() {}

func (x *QueryFilter) ProtoReflect() protoreflect.Message {
	mi := &file_storage_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryFilter.ProtoReflect.Descriptor instead.
func (*QueryFilter) Descriptor() ([]byte, []int) {
	return file_storage_common_proto_rawDescGZIP(), []int{7}
}

func (x *QueryFilter) GetColumn() string {
	if x != nil {
		return x.Column
	}
	return ""
}

func (x *QueryFilter) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *QueryFilter) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

// Status represents operation status
type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       []string               `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_storage_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_storage_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_storage_common_proto_rawDescGZIP(), []int{8}
}

func (x *Status) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Status) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Status) GetDetails() []string {
	if x != nil {
		return x.Details
	}
	return nil
}

// Health check messages
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_storage_common_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_common_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_storage_common_proto_rawDescGZIP(), []int{9}
}

func (x *HealthCheckRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Status        HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=storage.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	Message       string                            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     *timestamppb.Timestamp            `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_storage_common_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_common_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_storage_common_proto_rawDescGZIP(), []int{10}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_UNKNOWN
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthCheckResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Metrics and monitoring
type Metrics struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RecordsIngested    int64                  `protobuf:"varint,1,opt,name=records_ingested,json=recordsIngested,proto3" json:"records_ingested,omitempty"`
	QueriesProcessed   int64                  `protobuf:"varint,2,opt,name=queries_processed,json=queriesProcessed,proto3" json:"queries_processed,omitempty"`
	StorageSizeBytes   int64                  `protobuf:"varint,3,opt,name=storage_size_bytes,json=storageSizeBytes,proto3" json:"storage_size_bytes,omitempty"`
	IndexSizeBytes     int64                  `protobuf:"varint,4,opt,name=index_size_bytes,json=indexSizeBytes,proto3" json:"index_size_bytes,omitempty"`
	CpuUsagePercent    float64                `protobuf:"fixed64,5,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	MemoryUsagePercent float64                `protobuf:"fixed64,6,opt,name=memory_usage_percent,json=memoryUsagePercent,proto3" json:"memory_usage_percent,omitempty"`
	ActiveConnections  int64                  `protobuf:"varint,7,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	LastUpdated        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	mi := &file_storage_common_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_storage_common_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_storage_common_proto_rawDescGZIP(), []int{11}
}

func (x *Metrics) GetRecordsIngested() int64 {
	if x != nil {
		return x.RecordsIngested
	}
	return 0
}

func (x *Metrics) GetQueriesProcessed() int64 {
	if x != nil {
		return x.QueriesProcessed
	}
	return 0
}

func (x *Metrics) GetStorageSizeBytes() int64 {
	if x != nil {
		return x.StorageSizeBytes
	}
	return 0
}

func (x *Metrics) GetIndexSizeBytes() int64 {
	if x != nil {
		return x.IndexSizeBytes
	}
	return 0
}

func (x *Metrics) GetCpuUsagePercent() float64 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *Metrics) GetMemoryUsagePercent() float64 {
	if x != nil {
		return x.MemoryUsagePercent
	}
	return 0
}

func (x *Metrics) GetActiveConnections() int64 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *Metrics) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

var File_storage_common_proto protoreflect.FileDescriptor

const file_storage_common_proto_rawDesc = "" +
	"\n" +
	"\x14storage/common.proto\x12\astorage\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x1a\n" +
	"\bTenantID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1a\n" +
	"\bEntityID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x84\x01\n" +
	"\bRecordID\x12.\n" +
	"\ttenant_id\x18\x01 \x01(\v2\x11.storage.TenantIDR\btenantId\x12.\n" +
	"\tentity_id\x18\x02 \x01(\v2\x11.storage.EntityIDR\bentityId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\"h\n" +
	"\bSchemaID\x12.\n" +
	"\ttenant_id\x18\x01 \x01(\v2\x11.storage.TenantIDR\btenantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x05R\aversion\"\xd7\x02\n" +
	"\n" +
	"DataRecord\x12!\n" +
	"\x02id\x18\x01 \x01(\v2\x11.storage.RecordIDR\x02id\x12+\n" +
	"\x04data\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x04data\x12)\n" +
	"\x06schema\x18\x03 \x01(\v2\x11.storage.SchemaIDR\x06schema\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x03R\aversion\x12=\n" +
	"\bmetadata\x18\x06 \x03(\v2!.storage.DataRecord.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x90\x01\n" +
	"\bLocation\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x03R\x06length\x12\x1b\n" +
	"\trow_group\x18\x04 \x01(\x05R\browGroup\x12\x1e\n" +
	"\n" +
	"compressed\x18\x05 \x01(\bR\n" +
	"compressed\"k\n" +
	"\tTimeRange\x120\n" +
	"\x05start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\"o\n" +
	"\vQueryFilter\x12\x16\n" +
	"\x06column\x18\x01 \x01(\tR\x06column\x12\x1a\n" +
	"\boperator\x18\x02 \x01(\tR\boperator\x12,\n" +
	"\x05value\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\x05value\"P\n" +
	"\x06Status\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\adetails\x18\x03 \x03(\tR\adetails\".\n" +
	"\x12HealthCheckRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"\xfe\x01\n" +
	"\x13HealthCheckResponse\x12B\n" +
	"\x06status\x18\x01 \x01(\x0e2*.storage.HealthCheckResponse.ServingStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"O\n" +
	"\rServingStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x02\x12\x13\n" +
	"\x0fSERVICE_UNKNOWN\x10\x03\"\x85\x03\n" +
	"\aMetrics\x12)\n" +
	"\x10records_ingested\x18\x01 \x01(\x03R\x0frecordsIngested\x12+\n" +
	"\x11queries_processed\x18\x02 \x01(\x03R\x10queriesProcessed\x12,\n" +
	"\x12storage_size_bytes\x18\x03 \x01(\x03R\x10storageSizeBytes\x12(\n" +
	"\x10index_size_bytes\x18\x04 \x01(\x03R\x0eindexSizeBytes\x12*\n" +
	"\x11cpu_usage_percent\x18\x05 \x01(\x01R\x0fcpuUsagePercent\x120\n" +
	"\x14memory_usage_percent\x18\x06 \x01(\x01R\x12memoryUsagePercent\x12-\n" +
	"\x12active_connections\x18\a \x01(\x03R\x11activeConnections\x12=\n" +
	"\flast_updated\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdatedB\n" +
	"Z\b/storageb\x06proto3"

var (
	file_storage_common_proto_rawDescOnce sync.Once
	file_storage_common_proto_rawDescData []byte
)

func file_storage_common_proto_rawDescGZIP() []byte {
	file_storage_common_proto_rawDescOnce.Do(func() {
		file_storage_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storage_common_proto_rawDesc), len(file_storage_common_proto_rawDesc)))
	})
	return file_storage_common_proto_rawDescData
}

var file_storage_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_storage_common_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_storage_common_proto_goTypes = []any{
	(HealthCheckResponse_ServingStatus)(0), // 0: storage.HealthCheckResponse.ServingStatus
	(*TenantID)(nil),                       // 1: storage.TenantID
	(*EntityID)(nil),                       // 2: storage.EntityID
	(*RecordID)(nil),                       // 3: storage.RecordID
	(*SchemaID)(nil),                       // 4: storage.SchemaID
	(*DataRecord)(nil),                     // 5: storage.DataRecord
	(*Location)(nil),                       // 6: storage.Location
	(*TimeRange)(nil),                      // 7: storage.TimeRange
	(*QueryFilter)(nil),                    // 8: storage.QueryFilter
	(*Status)(nil),                         // 9: storage.Status
	(*HealthCheckRequest)(nil),             // 10: storage.HealthCheckRequest
	(*HealthCheckResponse)(nil),            // 11: storage.HealthCheckResponse
	(*Metrics)(nil),                        // 12: storage.Metrics
	nil,                                    // 13: storage.DataRecord.MetadataEntry
	(*structpb.Struct)(nil),                // 14: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),          // 15: google.protobuf.Timestamp
	(*structpb.Value)(nil),                 // 16: google.protobuf.Value
}
var file_storage_common_proto_depIdxs = []int32{
	1,  // 0: storage.RecordID.tenant_id:type_name -> storage.TenantID
	2,  // 1: storage.RecordID.entity_id:type_name -> storage.EntityID
	1,  // 2: storage.SchemaID.tenant_id:type_name -> storage.TenantID
	3,  // 3: storage.DataRecord.id:type_name -> storage.RecordID
	14, // 4: storage.DataRecord.data:type_name -> google.protobuf.Struct
	4,  // 5: storage.DataRecord.schema:type_name -> storage.SchemaID
	15, // 6: storage.DataRecord.timestamp:type_name -> google.protobuf.Timestamp
	13, // 7: storage.DataRecord.metadata:type_name -> storage.DataRecord.MetadataEntry
	15, // 8: storage.TimeRange.start:type_name -> google.protobuf.Timestamp
	15, // 9: storage.TimeRange.end:type_name -> google.protobuf.Timestamp
	16, // 10: storage.QueryFilter.value:type_name -> google.protobuf.Value
	0,  // 11: storage.HealthCheckResponse.status:type_name -> storage.HealthCheckResponse.ServingStatus
	15, // 12: storage.HealthCheckResponse.timestamp:type_name -> google.protobuf.Timestamp
	15, // 13: storage.Metrics.last_updated:type_name -> google.protobuf.Timestamp
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_storage_common_proto_init() }
func file_storage_common_proto_init() {
	if File_storage_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_common_proto_rawDesc), len(file_storage_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_storage_common_proto_goTypes,
		DependencyIndexes: file_storage_common_proto_depIdxs,
		EnumInfos:         file_storage_common_proto_enumTypes,
		MessageInfos:      file_storage_common_proto_msgTypes,
	}.Build()
	File_storage_common_proto = out.File
	file_storage_common_proto_goTypes = nil
	file_storage_common_proto_depIdxs = nil
}
