global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'storage-services'
    static_configs:
      - targets: 
        - 'auth-gateway:8080'
        - 'tenant-node:8000'
        - 'operation-node:8081'
        - 'cbo-engine:8082'
        - 'metadata-catalog:8083'
        - 'monitoring:8084'
