# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main.exe ./cmd/api"
  bin = "tmp/main.exe"
  include_ext = ["go"]
  exclude_dir = ["tmp"]
  exclude_file = []
  exclude_regex = []
  delay = 1000
  log = "air.log"
  send_interrupt = true
  kill_delay = 1000

[log]
  color = "true"
  timestamp = "true"

[screen]
  clear_on_rebuild = true
