# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main.exe ./cmd/api"
  bin = "tmp/main.exe"
  include_ext = ["go"]
  exclude_dir = ["tmp"]
  delay = 1000
  log = "air.log"
  send_interrupt = true

[log]
  color = "true"
  timestamp = "true"
