apiVersion: v1
kind: Namespace
metadata:
  name: storage-system
  labels:
    name: storage-system

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: storage-config
  namespace: storage-system
data:
  s3-endpoint: "s3.amazonaws.com"
  kafka-brokers: "kafka:9092"
  log-level: "info"

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: storage-system
type: Opaque
data:
  # Base64 encoded values
  url: cG9zdGdyZXM6Ly9wb3N0Z3JlczpwYXNzd29yZEBwb3N0Z3Jlczo1NDMyL3N0b3JhZ2Vfc3lzdGVtP3NzbG1vZGU9ZGlzYWJsZQ==

---
apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
  namespace: storage-system
type: Opaque
data:
  # Base64 encoded values - replace with actual credentials
  access-key: QUtJQUlPU0ZPRE5ON0VYQU1QTEU=
  secret-key: d0phbHJYVXRuRkVNSS9LN01ERU5HL2JQeFJmaUNZRVhBTVBMRUtFWQ==

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ingestion-server-config
  namespace: storage-system
data:
  ingestion-server.yaml: |
    server:
      http_port: 8080
      grpc_port: 9090
      read_timeout: 30s
      write_timeout: 30s
      idle_timeout: 60s
    
    storage:
      type: "s3"
      local_path: "/data"
      s3:
        bucket: "storage-system-data"
        region: "us-east-1"
      
    wal:
      segment_size: 64MB
      retention_period: 7d
      flush_interval: 1s
    
    memtable:
      max_size: 128MB
      flush_threshold: 100MB
    
    compaction:
      strategy: "leveled"
      max_level: 7
      level_multiplier: 10
    
    metrics:
      enabled: true
      port: 9999
      path: "/metrics"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: query-server-config
  namespace: storage-system
data:
  query-server.yaml: |
    server:
      http_port: 8081
      grpc_port: 9091
      read_timeout: 30s
      write_timeout: 30s
      idle_timeout: 60s
      max_connections: 1000
    
    storage:
      type: "s3"
      s3:
        bucket: "storage-system-data"
        region: "us-east-1"
    
    query:
      max_concurrent_queries: 100
      query_timeout: 300s
      result_cache_size: 1GB
      result_cache_ttl: 1h
    
    metrics:
      enabled: true
      port: 9999
      path: "/metrics"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: data-processor-config
  namespace: storage-system
data:
  data-processor.yaml: |
    server:
      http_port: 8082
      grpc_port: 9092
      read_timeout: 30s
      write_timeout: 30s
      idle_timeout: 60s
    
    processing:
      batch_size: 10000
      flush_interval: 5s
      max_concurrent_jobs: 10
      job_timeout: 1h
    
    storage:
      type: "s3"
      s3:
        bucket: "storage-system-data"
        region: "us-east-1"
    
    compaction:
      enabled: true
      schedule: "0 2 * * *"  # Daily at 2 AM
      strategy: "leveled"
    
    metrics:
      enabled: true
      port: 9999
      path: "/metrics"
