apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-server
  namespace: storage-system
  labels:
    app: query-server
    tier: backend
    component: query
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: query-server
  template:
    metadata:
      labels:
        app: query-server
        tier: backend
        component: query
    spec:
      containers:
      - name: query-server
        image: ghcr.io/storage-system/query-server:latest
        ports:
        - containerPort: 8081
          name: http
        - containerPort: 9091
          name: grpc
        env:
        - name: CONFIG_PATH
          value: "/app/configs/query-server.yaml"
        - name: LOG_LEVEL
          value: "info"
        - name: POSTGRES_URL
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: url
        - name: S3_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: storage-config
              key: s3-endpoint
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: s3-secret
              key: access-key
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: s3-secret
              key: secret-key
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: config-volume
          mountPath: /app/configs
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: query-server-config
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: query-server-service
  namespace: storage-system
  labels:
    app: query-server
spec:
  selector:
    app: query-server
  ports:
  - name: http
    port: 8081
    targetPort: 8081
    protocol: TCP
  - name: grpc
    port: 9091
    targetPort: 9091
    protocol: TCP
  type: ClusterIP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: query-server-hpa
  namespace: storage-system
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: query-server
  minReplicas: 3
  maxReplicas: 15
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
